### ISSUE TITLE
Is useEffect recommended over onClick events?

### ISSUE THREAD

**Issue by lucasheim** [SAP-samples/ui5-webcomponents-sample-react#24]
Looking through the samples, all click events are being treated using the `useEffect` hook, adding listeners to the click event:

```javascript
useEffect(() => {
    saveBtn.current.addEventListener("click", handleSave);
    return () => {
      saveBtn.current.removeEventListener("click", handleSave);
    }
  }, [handleSave]);
```
I'm new to React, so I'm not really sure about what is the advantage of this approach over using the `onClick` event already available as default from the components, like this:

```javascript
<ui5-button design="Emphasized" onClick={handleSave}>Save</ui5-button>
```

What is the recommendation? `useEffect` should always be preferred over `onClick`?

**Comment by fifoosid** [comment]
Hi @lucasheim 

The reason not to use onClick in out sample app is the fact that React doesn't support customEvents yet.
Meanwhile, UI5 Web Components are firing custom events(not everywhere, but almost everywhere). One of the few places where onClick would work is the button.

On the other hand, if we take ui5-switch and place it in React app, you can't subscribe to the change event like ```onChange={handleChange()}```, because the event is custom.

So for most of UI5 Web Components, you will have to use useEffect, because of the React limitation(the fact that they don't support custom events).

Best regards,
Filip
